### ISSUE TITLE
Improve routing and send correct 404 status codes

### ISSUE THREAD

**Issue by scottbedard** [scottbedard/oc-vuetober-theme#10]
The `index.htm` page should be converted to a layout, and entry point pages should be generated that match all available routes. This will allow us to send the correct HTTP status code when a 404 page is hit.

**Comment by gridsystem** [comment]
Is there any other way of throwing a 404 @scottbedard ?

For instance on route `/blog/:id`, axios might not get a result from the api. How would you suggest redirecting to the 404 page with the correct header?

**Comment by scottbedard** [comment]
Currently, there aren't really good ways to do this. The only thing I can think of off the top of my head would be to register other pages beyond the catchall route, and perform your queries there before the javascript runs. This isn't great, and it would likely be a pain to set up.

If you're ok with not sending a 404 status code, you can easily set up the redirect using [vue-router navigation guards](https://router.vuejs.org/en/advanced/navigation-guards.html). This is how most SPA's I've seen work, and it seems to work just fine.

The only *good* way to solve this problem, with correct status codes, would be to [implement server side rendering](https://github.com/scottbedard/oc-vuetober-theme/issues/24). Hopefully in the future we can make SSR an option for Vuetober.

Closing this issue in favor of #24
