### ISSUE TITLE
Not sure how to use this

### ISSUE THREAD

**Issue by mpenna** [scottbedard/oc-vuetober-theme#12]
Sorry if this is not an issue but instead a question. I've been studying and getting to know both VueJS and OctoberCMS for some time now and I got pretty enthused when I stumbled upon this project of yours. Yesterday I tried to set up a demo project in order to test out your vuetober theme but sadly it didn't work. Could you offer a couple of words on how this is all supposed to work? My expectations were that upon setting up an OctoberCMS project -- as we usually do with new themes inside that platform --, this theme of yours would be added/downloaded and then activated from the backend. I did that (and I followed your installation instructions) but I got a 404 when navigating to the site's home-page.

**Comment by scottbedard** [comment]
It sounds like you just haven't run an `npm run build` yet. Unlike traditional October themes, these repo scaffolds out a single-page-application for you. Meaning that there is only one page that October knows about, and it points all routes at. When you run the build command, an `index.htm` file should be created and you'll be able to view your site. Let me know if you need any more help!

**Comment by mpenna** [comment]
Nice! Issuing the npm run build did do the trick. As expected a pages/index.htm has been created inside the theme folder. Well, now all that's left to do is for me to learn the ins and outs of your app/theme! lol. Thanks!

**Comment by scottbedard** [comment]
@mpenna great, let me know if you need any more help!

**Comment by mpenna** [comment]
Just checking...   For me here the home page is rendering completely empty/blank in the browser. I haven't digged around enough yet, so maybe this is normal, but I was kinda expecting to see something similar to the repo's demo that you made available.

**Comment by scottbedard** [comment]
The demo shows what you get with this theme out of the box. Assuming you have all your dependencies installed, it should look exactly the same. Can you should me what your `index.htm` file looks like?

**Comment by mpenna** [comment]
Sure... this is my pages/index.htm file (I couldn't make it look nice pasted as code...): 


[index.htm.txt](https://github.com/scottbedard/oc-vuetober-theme/files/697606/index.htm.txt)

**Comment by scottbedard** [comment]
I mean that looks fine, provided your theme directory is in fact called `oc-vuetober`. Are there any errors being logged to the console when you try to view your page?

**Comment by mpenna** [comment]
Yep, the theme folder is named "oc-vuetober". No errors whatsoever in the console unfortunately. I got Vue DevTools installed and its icon on Chrome's toolbar is "lit green" when browsing the page, but upon clicking on it a message box pops out saying that Vue.js is detected but DevTools inspection is  not available either because it's in "production mode" or because it has been "explicitly disabled by the author".

**Comment by scottbedard** [comment]
Hmm, without more information I don't know what to tell you about the production build. Is the development build working?

Run this command and hit `http://localhost:3000`
```bash
npm run dev
```

**Comment by mpenna** [comment]
I'm running this inside a Vagrant - Homestead VM. I use this setup for all my web development and every site there is configured with its own Nginx virtual host that I then can access from the host machine. If I run the "npm run dev" command, I can't reach this server from the host.
