### ISSUE TITLE
Question about development

### ISSUE THREAD

**Issue by DavidStrada** [scottbedard/oc-vuetober-theme#13]
Hi Scott, first off I would like to say It's really nice the way you have structure this vue plugin ( coherent ).

I have a question about dev env, I have tried to make it work however I haven't been able to either understand how to/or make it work at all ( on dev ).

My understanding with October CMS it's barely minimum ( I should have stated this before ), however I have worked with laravel for a long time so theres  that.

When I run either `npm run dev or yarn run dev` it does fire either `localhost:3000` or the `http://vuetober.october.dev` I'm running `october.dev` using vallet ( laravel ), however I always get a 404 when visiting any of the above ( local / vuetober .. ), As I understand october requires or tries to find a `index.htm` file on `pages/ ` dir non is being generated, hence the 404 ?

I have ran `npm or yarn` using `prod` and it does place `pages/index.htm` and then everything works there.

So I guess my question is, could you clarify how or what steps am I missing on these if any or if I'm completely nuts :) ..

Thanks!

**Comment by scottbedard** [comment]
It sounds like you just haven't built your entry point, just run `npm run build` (or `yarn run build` if you're using Yarn), and try booting up the dev server again. I've never used Valet, so I can't really advise on that.

**Comment by DavidStrada** [comment]
Ok so first build process to create the entry point pages/index.html and then dev server, ok thanks!

Thanks,
David
