### ISSUE TITLE
Just a workflow Question

### ISSUE THREAD

**Issue by Michael-Reich** [scottbedard/oc-vuetober-theme#18]
Forgive me for my newbie Questions. But maybe you can help me.

I created a fresh git for my new website and cloned the vuetober-theme into the theme folder. The code is on a aws server, bitbucket and my local machine. 

Do I have to install Mamp locally to get `npm run dev` working? Would be great if it would work without it.

**Comment by scottbedard** [comment]
Yes, since October CMS and Laravel are PHP tools, you will need to have mamp or something similar running.
