### ISSUE TITLE
unmet peer dependency

### ISSUE THREAD

**Issue by opichon** [scottbedard/oc-vuetober-theme#21]
oc-vuetober-theme@2.2.0 /Users/olivier/projects/cpuk/vuetober/themes/cpuk
├── UNMET PEER DEPENDENCY sinon@1.17.7

npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.

**Comment by scottbedard** [comment]
Closed by 525bd34b77e9cf088a5f7bc7030f147257f1a371
