### ISSUE TITLE
How to include Plugins in Vue components?

### ISSUE THREAD

**Issue by neil-nato** [scottbedard/oc-vuetober-theme#23]
I have installed a plugin called 'simple contact us', how should I include it on a vue component?

**Comment by scottbedard** [comment]
Hi, I recommend installing plugins in the boot file, and then using a separate file to set them up. You can use the `vue-router` plugin as an example.

First, create a file that tells Vue to use your desired plugin, and set it up however you need to.
https://github.com/scottbedard/oc-vuetober-theme/blob/master/src/app/plugins/router.js

Then, add a reference to your plugin installer in the boot file.
https://github.com/scottbedard/oc-vuetober-theme/blob/master/src/app/boot.js#L10-L13

Hope this helps, good luck!
