### ISSUE TITLE
 Failed to mount component during demo

### ISSUE THREAD

**Issue by pcable** [scottbedard/oc-vuetober-theme#25]
Hi, I've been attempting to follow your tutorials but I'm not getting any output on my page.

I receive the following error
 Failed to mount component: template or render function not defined
From what I've seen online I need to use the standalone version of Vue however I'm a bit lost as to how to achieve this. Could you possibly update your tutorial with some information on how to get the standalone vue version.

**Comment by scottbedard** [comment]
Hi,

Your root component should be able to mount as long as [this selector](https://github.com/scottbedard/oc-vuetober-theme/blob/master/src/main.js#L21) correctly targets [this element](https://github.com/scottbedard/oc-vuetober-theme/blob/master/src/index.htm#L26). If you show me your `index.html` and `main.js` file I'd be happy to take a look.

I recommend using the runtime-only build of Vue, but if you'd like to use the stand alone version the easiest way to do this is to set an alias in your [base webpack configuration](https://github.com/scottbedard/oc-vuetober-theme/blob/master/build/webpack.base.conf.js), similar to how we're doing it in the [test environment](https://github.com/scottbedard/oc-vuetober-theme/blob/master/build/webpack.test.conf.js#L19-L20).

**Comment by pcable** [comment]
Thanks for getting back to me Scott.

I think i mislead you on that one. The project works when I clone the repository. It's just the hello.vue component that didn't render anything. 

So I've gone back and looked the differences between hello and the video component (something I should have done yesterday) and the only change seems to be that the ones that worked were loaded with an `import` call and the failing one was loaded using require. I'm not sure of the exactly why that would cause a problem but it loads fine when done with an import.

Thanks for the help. Loving the framework so far

**Comment by scottbedard** [comment]
Ah, glad you straightened it out. The breaking changes in [`vue-loader 13.0.0`](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0) are what's to blame for this. If you want to still use require, you'll need to tack on a `.default` to the end of it. Best of luck!
