### ISSUE TITLE
Favicon true way

### ISSUE THREAD

**Issue by xtsidx** [scottbedard/oc-vuetober-theme#29]
Hello, I really like how you combined these two frameworks! )

I have a question: 

Which is the TRUE way for set Favicon on this theme?

**Comment by scottbedard** [comment]
Thanks, glad you like it. As for a favicon, putting your `<link>` tag [somewhere in here](https://github.com/scottbedard/oc-vuetober-theme/blob/master/src/index.htm#L13-L24) should do the trick!

**Comment by scottbedard** [comment]
Ah, I see what you were asking now. Yup, that's how I would do it, glad you figured it out!
