### ISSUE TITLE
Scaffolding Reactive SPA with only browser

### ISSUE THREAD

**Issue by Piterden** [scottbedard/oc-vuetober-theme#3]
Hi, Scott!

I really love VueJS and I think that October CMS is one of the best CMS for present time.
I has ideas similar to yours about scaffolding Vue within October backend but I change some different way. This is plugin way and I have started to build it https://github.com/Piterden/oc-vuemanager

I know that I will need theme (often only one page) even if we change the plugin way. I suggest to have  a theme like dependency of plugin.

Take a look at my plugin, it similar with Cms module of October CMS and has 4 main sections:

- Vue Components Partials
- Vue Components Router Views
- JavaScript Files
- Compiler & Configs

### Vue Components Partials
Contains crud table of reusable vue components which we use like part of web page or viewport

### Vue Components Router Views
Contains crud table router views - the pages of our app

### JavaScript Files
Crud table for files from js folder of app. For example app.js, main.js, router.js, etc.

### Compiler & Configs
Here we have `gulpfile.js`, `webpack.config.js`, `package.json` edit forms. Also we can see compiler actions panel which have `npm install`, `npm run dev`, `npm run prod` and any you want (I suppose it's not secure to give to user promt, but we can generate buttons for scripts in `package.json`)

### Forms
Every Vue component crud edit form have script, style and template tabs with codeeditors and we can use right syntax highlighting for each editor. Components stored in database. When you save component from its data creating `.vue` file in filesystem.

The problem will be to realize realtime bash output in browser, but it is possible.

This plugin should allows users to scaffold Vue SPA from browser only.
I propose to combine our packages. If you have interested, please let me know.

Denis.

**Comment by scottbedard** [comment]
Hi Denis,

I'm not sure I fully understand what you're proposing. Do you mean you want to be able to edit `.vue` theme files from October's cms backend? That would be pretty cool, and there is no reason why that wouldn't work already. We'd just need to run webpack after the files have been changed.

**Comment by Piterden** [comment]
Sorry about my english.

Yes I proposing to edit `.vue` files directly from cms backend, and also to run webpack from there too.
It's like we have php shared hosting with npm pre-installed and then we can easily begin to scaffold reactive SPA with state control and other cool stuff.

If you like this, I need some help with implementation of realtime bash output stream. All another trivial round jobs I can do myself, but I has few tries with this stream (symfony & native php) and get a fiasko.

**Comment by scottbedard** [comment]
You can set up a bash script to simply execute the command, and collect it's output with this
https://github.com/scottbedard/oc-webhooks-plugin/blob/master/models/Hook.php#L98

I'm sorry though, I don't have time to collaborate on this project at the moment. My efforts with this repo are geared towards getting the Vue 2.0 version ready to go. Best of luck, this will be a cool tool if you can get it working!
