### ISSUE TITLE
3.0 Release

### ISSUE THREAD

**Issue by scottbedard** [scottbedard/oc-vuetober-theme#39]
We've tagged a release candidate for 3.0, so it's time to start getting the adjacent tooling ready to go.

### Screencasts

- [x] Getting started (from scratch)
  - Overview of what vue-cli is now, and how Vuetober has changed from v2
  - Create a basic Vuetober theme, and demonstrate the dev server / production builds
  - Possibly demonstrate how to create a Vuetober preset for rapid project scaffolding
- [ ] Getting started (from pre-configured SPA)
  - Demonstrate basic global components, and how to re-style them or register new ones.
  - Demonstrate adding routes, possibly demonstrate how layout components work.
- [ ] Using the GUI
  - Building production assets, and demonstrate the built in webpack analysis
  - Installing dependencies and plugins. Possibly use [`vue-cli-plugin-moment`](https://github.com/scottbedard/vue-cli-plugin-moment) as an example. Doing this could also be a cool example of how the webpack analyzer is useful, and how it can help with debugging production assets.
  - How to avoid "configuration fatigue", show where the `Update All Plugins` button is
- [ ] Loading initial data from the server
  - Possibly demonstrate integration with [`RainLab.User`](https://github.com/rainlab/user-plugin) plugin
- [ ] Adding the main Vue libraries
  - Single page applications with vue-router
  - Basic Vuex integration
- [ ] Using more advanced tooling
  - ESLint
  - TypeScript
  - Unit and end-to-end testing
- [ ] Shipping modern ES2015+ bundles alongside legacy bundles for better performance
- [ ] How to inspect / customize the webpack configuration
- [ ] Deployments
  - Possibly demonstrate how to integrate with Laravel Forge & Envoyer for zero downtime deployments

### Pre-configured SPA

Before releasing 3.0, the pre-configured SPA needs to be cleaned up and have all features implemented. See https://github.com/scottbedard/vuetober-spa/issues for more information.

**Comment by amdad** [comment]
👍

**Comment by scottbedard** [comment]
@amdad I'd be curious to hear your perspective on all of this. As someone who's used Vuetober, what did you find easiest / most difficult? I don't want the 3.x release to be intimidating to people who haven't used a Vuetober theme before. Also, have you tried 3.x yet? If so, what were your initial thoughts? I'd love to get some feedback from people before releasing it :)

**Comment by amdad** [comment]
Sory for delay. but I need a little bit free time to test things out and give my opinion. Next week.

Overall I think new version is great great. But I have some concerns I need to clarify.

**Comment by Teranode** [comment]
One thing that would be good to implement is SSR. I'm not sure what the process would be with october
