### ISSUE TITLE
package.json generation err.

### ISSUE THREAD

**Issue by wsd1** [scottbedard/oc-vuetober-theme#4]
When I use "vue init scottbedard/oc-vuetober-theme vuetheme" without unit test features, I always get a invalid package.json. There will be a ',' behind   "build": "node build/build.js". This will cause npm install error.

"scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",   <------ here 
    {{#unit}}
    "test": "karma start test/unit/karma.conf.js --single-run"{{#lint}},{{/lint}}
    {{/unit}}
    {{#lint}}
    "lint": "eslint --fix --ext .js,.vue src test/unit/specs test/e2e/specs"{{/lint}}
  },

**Comment by scottbedard** [comment]
Ah thanks, good catch! I'll fix this tonight, or feel free to submit a PR.

**Comment by scottbedard** [comment]
Closed by 04ca3badc7fde010d14da9598037dd09b0cd925b
