### ISSUE TITLE
Yarn run dev hangs the browser down

### ISSUE THREAD

**Issue by yevgenatlanov** [scottbedard/oc-vuetober-theme#41]
Hi, 

I follow to all steps and can't get my version up and running. Theme compiles well using yarn run build / npm run build and works with october, but the yarn run dev - don't run in the browser, it compiles well, browsersync loads well, console writes that everything was compiled and running - but the app doesn't load in the browser and even hangs it after infinite loading. 

node -v 10+
I've tried older issues - no luck so far.
How can i solve this problem?
Thanks in advance.

**Comment by scottbedard** [comment]
Hi, sorry you're having trouble. It sounds like maybe there is an issue with the dev proxy, but I don't have enough information to dive into this further. Would you mind uploading your theme repo to github so I can see how your setup looks?

**Comment by scottbedard** [comment]
Closing this issue, as there is not enough information to reproduce the problem. We can reopen it if a reproduction repo is created, or if more information is provided.
