### ISSUE TITLE
Global component not working

### ISSUE THREAD

**Issue by LarBearrr** [scottbedard/oc-vuetober-theme#43]
Following the video on creating global components and the button is not displaying on the page. It does seem to exist in the Vue inspector, just don't see it on the page. Any ideas?

**Comment by scottbedard** [comment]
I believe the syntax changed in Vue 2.4, and that video pre-dates it. Give the following a try and let me know if it works. If it doesn't, are you seeing any errors in the console?

```js
import buttonComponent from './path/to/button.vue';

export default {
    'v-button': buttonComponent,
};
```

**Comment by LarBearrr** [comment]
Perfect, thanks so much for the speedy reply. I'm pretty comfortable with October, just learning Vue so figuring out how they can work together is proving challenging. 

Great work here though and thanks for your contributions!
