### ISSUE TITLE
Dev server not rendering anything

### ISSUE THREAD

**Issue by LarBearrr** [scottbedard/oc-vuetober-theme#44]
I'm trying to implement https://github.com/coreui/coreui-free-vue-admin-template here and can't seem to get `npm run dev` to render anything. Everything compiles fine and says that it is listening; however, visiting http://localhost:3000 just keepings loading.

What's strange is that if I go up to the october level and run `php artisan serve` I can view the site just fine. 

Any thoughts?

**Comment by scottbedard** [comment]
Hmm, I've never tried using the dev server in combination with php artisan serve... Perhaps playing around with your dev proxy can solve this? You can find that value [here](https://github.com/scottbedard/oc-vuetober-theme/blob/master/build/dev-server.js#L67), and it should probably match whatever url you're using to hit the website with your artisan serve command.

**Comment by LarBearrr** [comment]
Are you sure? I'm following your video https://www.youtube.com/watch?v=nv55CLfWBcQ and you use `npm run dev` there to utilize hot loading, etc.

**Comment by scottbedard** [comment]
The dev command only starts the webpack server, which handles your frontend assets. If you're using `artisan serve` to run October itself, you'll need to have that running in addition to the webpack dev server. From there, making sure that your dev proxy is pointed at the url serving your October application should solve your problem.

**Comment by LarBearrr** [comment]
Ahhh, ok. That makes more sense. Sorry for the trivial questions and thanks again for the speedy reply. Let me give that a go and if everything works out, I'll close this issue.

**Comment by LarBearrr** [comment]
Perfect. Just in case anyone has similar questions in the future, make sure you are running `php artisan serve` and then `npm run dev`

Thanks Scott, excited about what this can do for my next app!

**Comment by scottbedard** [comment]
Great, glad you were able to get it working! And if you think the 2.x version of vuetober is exciting, just wait until you see 3.x. I'm currently working on tutorial videos for it, and hopefully it'll be ready to launch soon :)
