### ISSUE TITLE
Resources fail to load

### ISSUE THREAD

**Issue by wys-is-wyg** [scottbedard/oc-vuetober-theme#45]
Scott, I think this is an awesome project. I'm using it to teach students how to create a front-end app from an API with Vue. I would love for them to be able to use this module.

I hate to bother you, but I really would love to solve this. I tried to build an app with the older webpack based version, and then switched to this much cleaner build, as the students would have less to contend with. However, I'm getting the same problem as I had when I tried to adapt your webpack version. 

Setting baseUrl is working, but each css or js resource returns the home page on the front-end of October. I suspect the issue is with my implementation. I run `yarn build` with the baseUrl set to my theme folder, but they all return 404 errors. If you get time, I'd love your feedback on this.

Here is my vue config:
```
const path = require('path');
const webpack = require('webpack');
const config = require('./config/index.js');
var isProduction = process.env.NODE_ENV === 'production';
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  baseUrl: isProduction
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath,
  outputDir: '/assets/',
  configureWebpack: {
    resolve: {
      extensions: ['.js'],
      alias: {
        'jquery': 'jquery/dist/jquery.slim.js',
      }
    },
    plugins: [
      new webpack.ProvidePlugin({
        '$': 'jquery',
        jQuery: 'jquery',
        Popper: ['popper.js', 'default'],
        'Util': "exports-loader?Util!bootstrap/js/dist/util"
      }),
      // minify our root .htm file and inject production assets
      new HtmlWebpackPlugin({
          chunksSortMode: 'dependency',
          filename: path.resolve(__dirname, 'pages/index.htm'),
          inject: true,
          minify: {
              collapseWhitespace: true,
              removeAttributeQuotes: true,
              removeComments: true,
          },
          template: 'src/template/index.htm',
      }),
    ]
  },
}
```
I have copied your config from your "opinionated" version, and this is my config/index.js:
```
var path = require('path');

module.exports = {
    build: {
        assetsPublicPath: '/themes/themename/assets/',
        assetsRoot: path.resolve(__dirname, '../assets'),
        assetsSubDirectory: 'static',
        bundleAnalyzerReport: false,
        env: require('./prod.env'),
        productionGzip: false,
        productionGzipExtensions: ['js', 'css'],
        productionSourceMap: true,
    },
    dev: {
        assetsPublicPath: '/',
        assetsSubDirectory: 'static',
        autoOpenBrowser: true,
        cssSourceMap: false,
        env: require('./dev.env'),
        proxyTable: {},
    },
};
```

Here is a snippet of the built theme index.htm:
```
<html class="no-js" lang="en">
<head><meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
...
<link href="/themes/themename/assets/css/chunk-vendors.f5b6289e.css" rel="stylesheet">
<link href="/themes/themename/assets/css/app.0811f92a.css" rel="stylesheet">
</head>
```
So I am mystified why I get the home page served for every resource. Here's what the css file downloads as:
```
<!DOCTYPE html><html class=no-js lang=en><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="ie=edge">etc
```

Thanks for your time...

**Comment by scottbedard** [comment]
Hmm, this is tricky to debug looking at the compiled output. Would you be able to upload the theme to a GitHub repo so myself or others can clone it down and take a look?

**Comment by wys-is-wyg** [comment]
Thanks for that, I have just figured it out, actually, it was my .htaccess. Thanks for your time ;-)
