### ISSUE TITLE
Can I change entry route "/:all?*" to other path?

### ISSUE THREAD

**Issue by wsd1** [scottbedard/oc-vuetober-theme#5]
By default, theme's entry page is "Index" with its routing "/:all?*". But I want set up my own entry page, in which I can link to vue theme SPA.  

I this way, I can use user plugin to manage login stuff.  It is a bit hard for me to manage login process via ajax.

What do you think?

**Comment by scottbedard** [comment]
If you really wanted to, you could modify the source index path here
https://github.com/scottbedard/oc-vuetober-theme/blob/master/template/src/index.htm#L2

I generally handle auth by creating a plugin with endpoints to send the requests to. If you were really determined you could achieve the same thing with theme files, but I don't see much benefit to that.

**Comment by wsd1** [comment]
Thanks for your reply. Can you give me some clue on how to handle authentication via ajax? This is better option I think. 
Actually I'm a embedded software engineer, hardware is my favorite, PHP is a bit hard for me. ;-). I have tried google "october CMS ajax login", but little result meet my need.

**Comment by scottbedard** [comment]
I haven't done a great deal of token authentication, but this plugin might steer you in the right direction

https://github.com/gpasztor87/oc-jwt-auth

**Comment by wsd1** [comment]
Ha ha,  I  just dug in the same plugin. This is definitely a good demonstration ,  . Thanks.

**Comment by scottbedard** [comment]
Let me know how it goes! It might be nice adding RainLab.User authentication to this theme.
