### ISSUE TITLE
Vue materiails integration

### ISSUE THREAD

**Issue by ribsousa** [scottbedard/oc-vuetober-theme#7]
Could you help me integrate vue-materials components in oc-vuetober-theme!

https://github.com/johnleider/vue-materials

I installed via npm

`npm install vue-materials`

Then I created a file called src\app\plugins\ **vue-materials.js** 

```
import Vue from 'vue'
import Materials from 'vue-materials'

Vue.use(Materials)

```

and added the require in file src\app\ **boot.js**

```
//
// Plugins
//
require('./plugins/vue-materials')

```

It's right?

thanks!

**Comment by scottbedard** [comment]
Hi, that is close, but you installed the package globally instead of locally.

You need to run

```bash
npm install --save vue-materials
```

or

```bash
npm install --save-dev  vue-materials
```

Note the `--save` or `--save-dev` flags. It doesn't really matter which you pick, it just depends on your preferences. Let me know if this helps, good luck!

**Comment by ribsousa** [comment]
It worked well now!
Thank you!
