### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ribsousa** [scottbedard/oc-vuetober-theme#9]
Implement pagination results?

**Comment by scottbedard** [comment]
Include a `page` parameter in the blog api request, and add settings in the backend to determine how many posts to display on each page.

https://github.com/scottbedard/rainlab-blog-api/blob/master/controllers/PostsController.php#L55-L59

**Comment by ribsousa** [comment]
In **list.vue** add parameter **this.$route.params**

```
methods: {
        fetchData() {
          const posts = BlogResource.getPosts(this.$route.params)
          this.$resources({ posts })
        }
      }
```
In **blog.js** add parameter **${page}**

```
	getPosts({ page }) {
    return Vue.http.get(`/api/rainlab/blog/${page}`)
  }
}
```

Not work!

**Comment by scottbedard** [comment]
http://router.vuejs.org/en/essentials/dynamic-matching.html
